config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :users
  resources :posts
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :creator, class_name: :User
  validates :creator, presence: true
  validates :content, presence: true
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: "creator_id", dependent: :destroy
  validates :name, :username, :email, presence: true
  validates :username, :email, uniqueness: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  # before_action :require_login

  def not_found
      raise ActionController::RoutingError.new('Not Found')
    rescue
      render_404
  end

  def render_404
    render file: "#{Rails.root}/public/404", status: :not_found
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    authorize!(@post.creator)
  end

  def update
    authorize!(@post.creator)
    if @post.update(post_params)
      redirect_to post_url, notice: 'post was updated.'
    else
      render 'edit'
    end
  end

  def destroy
    authorize!(@post.creator)
    @post.destroy
    redirect_to posts_url, notice: 'post was successfully deleted.'
  end

  private
  def set_post
    @post = find_and_ensure_entry(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :image, :creator_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip_before_action :require_login

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to root_url, notice: 'welcome!'
    else
      flash.now.alert = 'email or password is invalid.'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_url, notice: 'you have successfully logged out.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      log_in(@user)
      redirect_to root_url, notice: 'thank you for signing up!'
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorize!(user)
    redirect_to root_path unless authorized?(user)
  end

  def authorized?(user)
    current_user == user
  end

  def require_login
    unless current_user
      redirect_to login_url
    end
  end

  def find_and_ensure_entry(id)
    post = Post.find_by(id: id)
    not_found if post.nil?
    post
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TakeYourPic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header class="header">
        <h1><%= link_to "takeyourpic", root_path %></h1>
      </header>
      <nav class="navbar">
        <% if logged_in? %>
          <ul>
            <li>
              <%= link_to "add new post", new_post_path %>
            </li>
            <li>
              <%= link_to "logout", logout_path, method: :delete %>
            </li>
          </ul>
        <% end %>
      </nav>

      <div class="flash">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: "alert" %>
        <% end %>
      </div>

      <div class="main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="post-form">
  <%= form_for @post do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2>form is invalid.</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </div>
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <div class="actions">
      <%= f.submit "submit" %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="post">
  <% if post.image.attached? %>
    <div class="img">
      <%= link_to image_tag(post.image), post_path(post) %>
    </div>
  <% end %>
  <div class="content">
    <%= post.creator.username %>: <%= post.content %>
  </div>
  <div class="date">
    <%= post.created_at.strftime("%B %d, %Y").downcase %>
  </div>
</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render partial: "form", locals: {post: @post} %>

app/views/posts/index.html.erb
<div class="posts">
  <%= render(@posts) || "There are no posts yet." %>
</div>

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= render partial: "form", locals: {post: @post} %>

app/views/posts/show.html.erb
<div class="show-post">
  <div class="img">
    <%= image_tag @post.image.variant(resize: "540x540") %>
  </div>
  <div class="content">
    <%= @post.creator.username %>: <%= @post.content %>
  </div>
  <div class="date">
    <%= @post.created_at.strftime("%B %d, %Y").downcase %>
  </div>

  <% if authorized?(@post.creator) %>
    <div class="show-links">
      <%= link_to "edit post", edit_post_path(@post) %> |
      <%= link_to "delete post", post_path(@post), method: :delete, confirm: 'are you sure?' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>hello world</h1>

app/views/users/new.html.erb
<h1>sign up</h1>
<div class="signup-text">
  sign up to see photos and videos from your friends.
</div>
<div id="signup-form">
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>form is invalid.</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message.downcase %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.email_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit "sign up" %>
    </div>
  <% end %>
</div>
<div class="account">
  already have an account? <%= link_to "login", login_path %>
</div>